[package]
authors = ["Gavin Panella <gavinpanella@gmail.com>"]
name = "allenap-shell-utils"
version = "0.1.0"

[[bin]]
doc = false
name = "allenap-shell-utils"
path = "src/main.rs"

[dependencies]
clap = {version = "^3.2", features = ["default", "cargo", "env"]}
dirs = "^4.0.0"
